### ISSUE TITLE
Buy order problem

### ISSUE THREAD

**Issue by MahmutKutlukaya** [VermeirJellen/PoloniexR#3]
Many thanks for PoloniexR package. I have been working on it for a while. It is working perfectly well. However I am experiencing problems while using  the "buy" order. When I run the following code;
buy.order <- ProcessTradingRequest(poloniex.trading,
                                   command = poloniex.trading@commands$buy,
                                   args    = list(currencyPair      = "BTC_XMR",
                                                  rate              = 0.015,
                                                  amount            = 0.0005,
                                                  immediateOrCancel = 1))
I receive;
Error in ProcessTradingRequest(poloniex.trading, command = poloniex.trading@commands$buy,  : 
  Unable to connect to https://poloniex.com/tradingApi? (422)
Your help is much appreciated.

**Comment by VermeirJellen** [comment]
Hey MahmutKutlukaya,

You seem to be encountering [this issue](https://github.com/VermeirJellen/PoloniexR/issues/4), to which I just gave a reply. I'm guessing you have been performing parallel calls, causing the Poloniex request nonce logic to fail. Renewing your key/secret and using the pair for your R application only could help.

**Comment by MahmutKutlukaya** [comment]
Hi Jellen,
Many thanks for your kind reply. I realized that Poloniex does not allow
buy and sell orders under certain limits (which are unknown) through its
API. When I increased the order size the problem is solved.
Just wanted to inform you.
Kind regards,

Mahmut KUTLUKAYA, PhD, FRM
